apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orpheus-ingress
spec:
  tls:
  - secretName: orpheus-certchain
  rules:
  - host: orphe.us
    http:
      paths:
      - backend:
          serviceName: orpheus-service
          servicePort: 3000
