apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mindthegap-orpheus-ingress
spec:
  tls:
  - secretName: mindthegap-orpheus-certchain
  rules:
  - host: orphe.us
    http:
      paths:
      - backend:
          serviceName: mindthegap-orpheus-service
          servicePort: 3000
